---
title: "Differential expression & genotype-expression correlation of PICALM in AD, nonAD and all"
author: "XSun"
date: "2024-06-28"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
---

# Introduction

We address the one of the comment from the reviewer here. 

1.postmortem brain microglia AD vs. nonAD differential expression analysis of PICALM

2. genotype-expression correlation of PICALM. 

```{r warning=F, message=F}

df <- readxl::read_excel("/project2/xinhe/xsun/psych_analysis/2.review/PICALM_CPM_df_2_plot_AD_control_genotype_NG2022.xlsx",sheet=3)
colnames(df) <- c("sample","Diag","Genotype","eQTL_diagnosis","PICALM_expression","average_expr_group")

df <- df[,1:5]

DT::datatable(df,caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Individual level PICALM expression'),options = list(pageLength = 5) )
```


# Differential expression analysis of PICALM


# Genotype-expression correlation of PICALM

1. The dataset was divided into three groups:

- All samples
- Alzheimer Disease (AD) samples
- Non-Alzheimer Disease (nonAD) samples

2. Correlation Analysis:

For each group (all samples, AD, and nonAD), the correlation between PICALM expression and genotype was calculated using

- Pearson correlation test: measures the strength and direction of the linear relationship between two continuous variables
- ANOVA: is used to compare the means of three or more groups to see if at least one group mean is different from the others


## Pearson correlation test


cor.test().
Additionally, summary statistics (mean, standard deviation, and count) for PICALM expression in each genotype group were computed.




